"use strict";

module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert(
      "Bosses",
      [
        {
          bossNames: "E. Black Mage",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "E. Chosen Seren",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "H. Black Mage",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "C. Kaos The Gaurdian",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "H. Chosen Seren",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "N. Chosen Seren",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "H. Versus Hilla",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "H. Darknell",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "C. Gloom",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "C. Guardian Angel Slime",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "N. Versus Hilla",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "H. Will",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "H. Lucid",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "H. Lotus",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "H. Damien",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "N. Darknell",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "N. Gloom",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "N. Will",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "N. Lucid",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "E. Will",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "E. Lucid",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "N. Guardian Angel Slime",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "N. Damien",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "N. Lotus",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Akechi Mitsuhide",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "C. Papulatus",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "C. Vellum",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "H. Magnus",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Princess No",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "C. Pierre",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "C. Von Bon",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "C. Zakum",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "C. Crimeson Queen",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "N. Cygnus",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "C. Pink Bean",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "H. Hilla",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "E. Cygnus",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "H. Mori Ranmaru",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "N. Papulatus",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "N. Magnus",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "N. Akarium",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "H. Von Leon",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "N. Von Leon",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "N. Pink Bean",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "C. Horntail",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "OMNI-CLN",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Frenzied Gigatoad",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "E. Arkarium",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "E. Von Lean",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "N. Horntail",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "N. Vellum",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "N. Crimson Queen",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "N. Von Bon",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "N. Pierre",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Gigatoad",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "E. Horntail",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Mori Ranmaru",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "N. Hilla",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Yakuza Boss",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "E. Magnus",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "E. Papulatus",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "N. Zakum",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "E. Zakum",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Flag",
          resetTime: "Weekly",
          category: "Quest",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Culver",
          resetTime: "Weekly",
          category: "Quest",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Monster Park",
          resetTime: "Daily",
          category: "Quest",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Maple Tour",
          resetTime: "Daily",
          category: "Quest",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Haven",
          resetTime: "Weekly",
          category: "Quest",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Dark World Tree",
          resetTime: "Weekly",
          category: "Quest",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Vanishing Journey",
          resetTime: "Daily",
          category: "Quest",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Chu Chu",
          resetTime: "Daily",
          category: "Quest",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Lachelein",
          resetTime: "Daily",
          category: "Quest",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Arcane",
          resetTime: "Daily",
          category: "Quest",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Morass",
          resetTime: "Daily",
          category: "Quest",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Esfera",
          resetTime: "Daily",
          category: "Quest",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Cernium",
          resetTime: "Daily",
          category: "Quest",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Arcus",
          resetTime: "Daily",
          category: "Quest",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Odium",
          resetTime: "Daily",
          category: "Quest",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  down: async (queryInterface, Sequelize) => {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     */
    await queryInterface.bulkDelete("Bosses", null, {});
  },
};
