"use strict";

module.exports = {
  up: async (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert(
      "Bosses",
      [
        {
          bossNames: "Extreme Black Mage",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Extreme Chosen Seren",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Hard Black Mage",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Chaos Kaos The Gaurdian",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Hard Chosen Seren",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Normal Chosen Seren",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Hard Versus Hilla",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Hard Darknell",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Chaos Gloom",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Chaos Guardian Angel Slime",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Normal Versus Hilla",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Hard Will",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Hard Lucid",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Hard Lotus",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Hard Damien",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Normal Darknell",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Normal Gloom",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Normal Will",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Normal Lucid",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Easy Will",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Easy Lucid",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Normal Guardian Angel Slime",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Normal Damien",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Normal Lotus",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Akechi Mitsuhide",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Chaos Papulatus",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Chaos Vellum",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Hard Magnus",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Princess No",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Chaos Pierre",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Chaos Von Bon",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Chaos Zakum",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Chaos Crimeson Queen",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Normal Cygnus",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Chaos Pink Bean",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Hard Hilla",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Easy Cygnus",
          category: "Boss",
          resetTime: "Weekly",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Hard Mori Ranmaru",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Normal Papulatus",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Normal Magnus",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Normal Akarium",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Hard Von Leon",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Normal Von Leon",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Normal Pink Bean",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Chaos Horntail",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "OMNI-CLN",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Frenzied Gigatoad",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Easy Arkarium",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Easy Von Lean",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Normal Horntail",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Normal Vellum",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Normal Crimson Queen",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Normal Von Bon",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Normal Pierre",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Gigatoad",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Easy Horntail",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Mori Ranmaru",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Normal Hilla",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Yakuza Boss",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Easy Magnus",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Easy Papulatus",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Normal Zakum",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          bossNames: "Easy Zakum",
          category: "Boss",
          resetTime: "Daily",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  down: async (queryInterface, Sequelize) => {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     */
    await queryInterface.bulkDelete("Bosses", null, {});
  },
};
